Don't truncate when dealing with unicode/encoded strings
colinbdclark/osc.js pull request #190
Opened 2022-02-18 20:12 UTC by bgola

When encoding unicode chars like `ç` osc.js writeString method would encode and convert the string to UInt8Array but still use the old string length, this results in incomplete bytes when constructing the final array.

For example:

`("çç" + "\u0000").length == 3`

if you encode that string you end up with an array with the length of 5, but with the old code the returned array was already created with the padded length of 4. in the end you have an incomplete string.

2022-02-18 21:23 UTC, jean-emmanuel commented
I haven''t had the time to check the logic behind the PR, but there are at leastt some syntax errors that should be fixed (see review notes).

2022-02-18 22:55 UTC, colinbdclark requested changes
Hi @bgola, thanks so much for this pull request, I really appreciate it. I've had a quick look at it, and left some suggestions on how to improve the implementation to the point where it could be usable.

2022-02-18 22:55 UTC, colinbdclark commented on src/osc.js
> +        len = terminated.length,
In JavaScript, assigment to variables that haven't been defined with ```var``` (or the preferable ```let``` statement, but osc.js' largely predates it) are implicitly defined as global variables. We should ensure they're properly defined here.

2022-02-18 22:55 UTC, colinbdclark commented on src/osc.js
> +            terminated = encoder(terminated);
Why did you decide to reassign to ```terminated``` instead of using ```encodedStr```?

2022-02-18 22:55 UTC, colinbdclark commented on src/osc.js
>              encodedStr;
This variable is now no longer used. Should it be, or should it be removed?

2022-02-18 23:27 UTC, bgola commented
> The other thing that would be helpful is to understand the context where you encountered the issue. Did you try to encode some strings and get an error somewhere higher up in the osc.js API? If so, can you share that information so that we can ensure we have sufficient tests at all levels of the library?

it doesn't fail above, it encodes wrong and I sends the OSC message via websocket. When I receive on my server side (a python app) and try to rebuild the string in python it fails because there is a byte missing.

Sorry for the rushed PR, I just wanted to point out the bug and where it happens! I am a bit busy (and that's how I ended up finding the bug ;)) but as soon as I have some time I can improve the PR if no one does in the meanwhile. Thanks for all the work :)

2022-04-13 16:54 UTC, colinbdclark commented
This fix was rolled into @jean-emmanuel #192 and released in osc.js v2.4.3. Thanks for your help and contributions, @bgola and @jean-emmanuel!

2022-04-13 16:54 UTC, closed without merging